### ISSUE TITLE
Small Inline Reaction Wheel - lights missplaced

### ISSUE THREAD

**Issue by bohni** [KSPSnark/IndicatorLights#13] opened 2020-11-15 10:00 UTC
![image](https://user-images.githubusercontent.com/1252254/99181858-90229b80-2731-11eb-95d0-80388a32158e.png)

These missplaced indicator lights are heating up on reentry!

KSP 1.10.1.2939 Windows
Making History 1.10.1
Breaking Grounds 1.5.1

**Comment by KSPSnark** [comment] 2020-11-15 13:58
Hi, and thanks for the bug report & suggested fix!

However... it looks as though you're not running the stock reaction wheel.  Perhaps you're running ReStock or something similar?

The indicator lights on the small reaction wheel are correctly placed in stock, and this issue does not occur in that case-- therefore this is not a bug in IndicatorLights per se, and the proposed fix in the pull request you've submitted would actually mess it up in the stock situation, even if it fixes it with whatever mod you're using.

Accordingly, I'm closing out this bug as "not reproducible"-- for _IndicatorLights_ itself.  Please note, however, that there's a _separate_ mod, IndicatorLights Community Extensions, which was provided specifically to create third-party compatibility with various mods.  That looks like exactly the scenario you're running into.

Therefore, I expect that the correct place for you to come up with a fix with this problem would be in IndicatorLights Community Extensions, rather than in IndicatorLights itself.  The forum discussion thread for it is located here:
https://forum.kerbalspaceprogram.com/index.php?/topic/149567-110-indicatorlights-community-extensions-v162-compatibility-patches-for-indicatorlights/

So, my recommendation to you would be to check out that mod, then come up with a patch to fix the issue and submit it there.  It will likely take the form of a ModuleManager patch, the gist of which is something like, "if _<specific mod>_ is installed, then _<apply fix>_".

**Closed as completed by KSPSnark** 2020-11-15 13:58 UTC

**Comment by bohni** [comment] 2020-11-15 15:36
Oh, sorry about that (I'm using Restock...) ! Should have checked that before posting! Thanks for the hint!
