### ISSUE TITLE
Blinking lights causing lag

### ISSUE THREAD

**Issue by Svish** [KSPSnark/IndicatorLights#4] opened 2018-04-13 23:44 UTC
When I rendevouz a ship, the lights on the target ship blinks (as described by the mod description). Unfortunately this blinking seems to cause some very annoying lag. Game runs smooth, I come close enough for the lights to start blinking, and I start getting lag spikes in the same "rhythm" as the lights blinking. Then when the lights eventually stop blinking, the lag spikes disappear and game runs smooth again. Very annoying... 😕

**Comment by KSPSnark** [comment] 2018-06-11 15:44
Sorry, I've never had this problem myself, everything works fine on my own system.  Would need specific, reliable repro steps for me to look at it.

If it turns out that it's not physically *possible* for me to reproduce it-- e.g. if it only occurs on a system with different hardware configuraiton than mine, or the like-- then the only way it would be practical to look at this would be if someone who *can* reproduce it could come up with a proposed fix of their own.

I'm sorry I couldn't be of more help, but I'd need more info to be able to do anything.

**Comment by KSPSnark** [comment] 2022-02-14 00:41
Never received any way of reproducing this, closing issue.

**Closed as completed by KSPSnark** 2022-02-14 00:41 UTC
