### ISSUE TITLE
Floating Light Textures

### ISSUE THREAD

**Issue by xPROxSLASHERx** [KSPSnark/IndicatorLights#16] opened 2021-07-21 10:30 UTC
Don't have a screenshot, but in an RP1 install the starting unmanned capsule (at least one of them, if not multiple, didn't dig too deep) had floating green lights or almost just blank textures floating about a meter away from the craft. Thought it was a glitch in the editor but the visual persisted into the game. Removed this mod as the first culprit and the issue was resolved. Installed through CKAN if that makes any difference.

**Comment by KSPSnark** [comment] 2022-02-14 00:38
Thank you for the report!  However, IndicatorLights doesn't include 3rd-party mod support, therefore closing this issue as "not a bug".

If you have a mod that causes a problem like this, and you'd like to supply a fix for it, please have a look at the [IndicatorLights Community Extensions](https://forum.kerbalspaceprogram.com/index.php?/topic/149567-112x-indicatorlights-community-extensions-v162-compatibility-patches-for-indicatorlights/) mod, which is where I accept community-supplied patches for 3rd-party mod support and the like.

**Closed as completed by KSPSnark** 2022-02-14 00:38 UTC

**Comment by Sileo35** [comment] 2022-05-31 23:16
> Don't have a screenshot, but in an RP1 install the starting unmanned capsule (at least one of them, if not multiple, didn't dig too deep) had floating green lights or almost just blank textures floating about a meter away from the craft. Thought it was a glitch in the editor but the visual persisted into the game. Removed this mod as the first culprit and the issue was resolved. Installed through CKAN if that makes any difference.

It's not here (but in commu extension) but I respond to him. You have to change the position of light in the file IndicatorLights_VenStockRevamp.cfg for the @PART[asasmodule1-2]
and you put the 4 lights at :
		position = -0.27, 0,0.27
		position = 0.27, 0,-0.27
		position = 0.27, 0,0.27
		position = -0.27, 0,-0.27
It's what I have done and it fix.
Cheers.
